# Generated by Django 3.2.12 on 2022-03-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20220313_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=240, unique=True),
        ),
    ]
