# Generated by Django 3.2.12 on 2022-03-13 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_participant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 17, 40, 18, 879410)),
        ),
        migrations.AddField(
            model_name='interviews',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 17, 40, 18, 879410)),
        ),
        migrations.AddField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 17, 40, 18, 879410)),
        ),
        migrations.AddField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 17, 40, 18, 879410)),
        ),
    ]
