# Generated by Django 3.2.12 on 2022-03-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20220313_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='title',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
    ]
