# Generated by Django 3.2.12 on 2022-03-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_rename_interviews_interview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['start_time']},
        ),
    ]
